development:
  GMAIL_USERNAME: your_email
  GMAIL_PASSWORD: your email password
  DATABASE_USER: justin
  DATABASE_PASSWORD: nitsujintranet
test:
  GMAIL_USERNAME: your_email
  GMAIL_PASSWORD: your email password
  DATABASE_USER: justin
  DATABASE_PASSWORD: nitsujintranet 
production:
  GMAIL_USERNAME: your_email
  GMAIL_PASSWORD: your email password
